### ISSUE TITLE
License missing in the gemspec definition

### ISSUE THREAD

**Issue by mensfeld** [trifle-io/trifle-stats#3]
Hey,

My name is Maciej Mensfeld and I run a research security project called WhiteSource https://diffend.io.

I've noticed, that this gem does not have a license definition in the gemspec but it does have an MIT license in the code.

While from the legal perspective it is enough, it can create a confusion for anyone looking at the gem page instead of downloading and unpacking sources (or going to GH):

![Zrzut ekranu z 2021-07-11 12-40-57](https://user-images.githubusercontent.com/392754/125191928-4305b380-e245-11eb-9234-ea7fb9178698.png)

Just wanted to let you know. Have a nice day :)

**Comment by jozefvaclavik** [comment]
@mensfeld Done. Thanks for pointing that out! 🍻
